[package]
name = "dock_sprout"
version = "0.2.1"
edition = "2021"

[[bin]]
name = "sprout"
path = "src/main.rs"

[dependencies]
gumdrop = "0.8.1"
ignore = "0.4.23"
walkdir = "2.4.0"

[dev-dependencies]
tempfile = "3.16.0"
